#!/usr/bin/env bash
# fix nginx in short way
chown nginx:nginx /etc/nginx/ -R
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx start
